SELECT * FROM practice_set.department;
CREATE TABLE DEPARTMENT(ID int, DEPT_ZONE varchar(30), DEPT_BLOCK varchar(5), DEPT_NAME varchar(20));

INSERT INTO DEPARTMENT VALUE('101','NORTH','B','IT');
INSERT INTO DEPARTMENT VALUE('102','SOUTH','A','FINACE');
INSERT INTO DEPARTMENT VALUE('103','WEST','B','MANAGEMENT');
INSERT INTO DEPARTMENT VALUE('104','EAST','C','CONSULTANT');
INSERT INTO DEPARTMENT VALUE('105','NORTH-EAST','D','RECEPTION');

ALTER TABLE department MODIFY DEPT_ZONE VARCHAR(25);

UPDATE department SET DEPT_BLOCK = 'E' WHERE ID = 103 ;

DELETE FROM department WHERE ID = 105;

TRUNCATE TABLE department;

DROP TABLE department;
